Haskify/Models/Category.cs
using System.Collections.Generic;

namespace Haskify.Models
{
    public class Category
    {
        public string CategoryName { get; set; }
        public List<string> CategoryExercises { get; set; } 
    }
}   

Haskify/Models/CategoryViewModel.cs
using System.Collections.Generic;
using System.Web;

namespace Haskify.Models
{
    public class CategoryViewModel
    {
        public List<Category> Categories { get; set; }
        public string Introduction { get; set; }

        public string IsCategoryActive(string category)
        {
            var path = HttpContext.Current.Request.Url.AbsolutePath;
            string[] pathParameters = path.Split('/');
            if (pathParameters.Length < 2) return "";

            var activeCategory = pathParameters[1];
            if (string.IsNullOrEmpty(activeCategory)) return "";

            var isActive = activeCategory == category ? "activeMenu" : "";
            return isActive;
        }

        public string IsExerciseActive(string exercise, string category)
        {
            var path = HttpContext.Current.Request.Url.AbsolutePath;
            string[] pathParameters = path.Split('/');

            if (pathParameters.Length < 2)
                return "";

            var activeCategory = pathParameters[1];

            var activeExercise = "Introduction";

            if(pathParameters.Length >= 3)
                activeExercise = pathParameters[2];
            if (string.IsNullOrEmpty(activeExercise) && string.IsNullOrEmpty(activeCategory))
                return "";

            var isActive = (activeExercise == exercise && activeCategory == category) ? "activeMenu" : "";
            return isActive;
        }
    }
}

Haskify/Models/Exercise.cs
using System.ComponentModel.DataAnnotations;

namespace Haskify.Models
{
    public class Exercise
    {
        public string FileName { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string Hint { get; set; }
        public string Solution { get; set; }
    }
}

Haskify/Models/ExerciseViewModel.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Haskify.Models
{
    public class ExerciseViewModel
    {

        public string ActiveCategory { get; set; }
        public IEnumerable<string> CategoryExercises { get; set; } 
        public Exercise ActiveExercise { get; set; }
        public string Result { get; set; }
        public string Introduction { get; set; }
        public string NextCategory { get; set; }
        public string NextExercise { get; set; }


        public void GetNextExercise()
        {
            var currentName = Path.GetFileNameWithoutExtension(ActiveExercise.FileName);
            var exercises = CategoryExercises.ToList();
            var nextExIndex = exercises.IndexOf(currentName) + 1;
            if (nextExIndex <= (exercises.Count - 1))
            {
                NextExercise = exercises[nextExIndex];
                NextCategory = ActiveCategory;
            }
            else
            {
                NextExercise = "";
            }
        }

        public string IsActive(string exercise)
        {
            if (ActiveExercise == null) return "";

            var isActive = ActiveExercise.FileName == (exercise + ".hs") ? "active" : "";
            return isActive;
        }

        public string IsActiveCategory(string category)
        {
            if (string.IsNullOrEmpty(ActiveCategory)) return "";

            var isActive = ActiveCategory == category ? "active" : "";
            return isActive;
        }
    }
}

Haskify/Controllers/ExerciseController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Haskify.Models;
using Haskify.Services;

namespace Haskify.Controllers
{
    public class ExerciseController : Controller
    {
        private IExerciseService _exerciseService;
        private string _title = "Haskify";
        private List<Category> _categories;

        public ExerciseController(IExerciseService exerciseService)
        {
            _exerciseService = exerciseService;
            _categories = new List<Category>();

            GetCategoryExercises();
        }

        private void GetCategoryExercises()
        {
            var categories = _exerciseService.GetAllCategories();

            foreach (var cat in categories)
            {
                var categoryExercises = _exerciseService.GetAllExercisesFromCategory(cat);
                _categories.Add(new Category()
                {
                    CategoryName = cat,
                    CategoryExercises = categoryExercises
                });
            }
        }

        // GET: Tutorial
        public ActionResult Index()
        {
            var model = new ExerciseViewModel();
            
            ViewBag.Title = _title;
            return View(model);
        }

        [Route("{category}")]
        public ActionResult CategoryPage(string category)
        {
            var exercises = _exerciseService.GetAllExercisesFromCategory(category);
            var introduction = _exerciseService.GetIntro(category);

            var model = new ExerciseViewModel
            {
                CategoryExercises = exercises,
                ActiveCategory = category,
                Introduction = introduction
            };

            ViewBag.Title = _title;
            return View("CategoryPage", model);
        }

        [Route("{category}/{exerciseName}/")]
        public ActionResult ExercisePage(string category, string exerciseName)
        {
            var exercise = _exerciseService.GetExercise(category, exerciseName);
            var exercises = _exerciseService.GetAllExercisesFromCategory(category);

            var model = new ExerciseViewModel
            {
                CategoryExercises = exercises,
                ActiveCategory = category,
                ActiveExercise = exercise,
                NextCategory = _exerciseService.GetNextCategory(category)
            };
            model.GetNextExercise();
            ViewBag.Title = _title;
            return View("ExercisePage", model);
        }

        public ActionResult GetCategories()
        {
            var model = new CategoryViewModel()
            {
                Categories = _categories
            };

            return PartialView("_Categories", model);
        }

        [HttpPost]
        [Route("{category}/{exerciseName}")]
        public ActionResult PostSolution(string category, string exerciseName, string userSolution)
        {
            var exercise = _exerciseService.GetExercise(category, exerciseName);
            var result = _exerciseService.CheckSolution(exercise, userSolution);
            var exercises = _exerciseService.GetAllExercisesFromCategory(category);

            var model = new ExerciseViewModel()
            {
                Result = result,
                ActiveExercise = exercise,
                CategoryExercises = exercises,
                ActiveCategory = category
            };
            model.GetNextExercise();

            return View("ExercisePage", model);
        }
    }
}

Haskify/Views/Exercise/CategoryPage.cshtml
@model Haskify.Models.ExerciseViewModel

<div class="jumbotron">
    <h1>@Model.ActiveCategory</h1>
    <p>@Html.Raw(Model.Introduction)</p>
    <p>
        <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" href="/@Model.ActiveCategory/1" role="button">Lets write some Haskell!</a>
    </p>
</div>

Haskify/Views/Exercise/ExercisePage.cshtml
@model Haskify.Models.ExerciseViewModel
@{
    var exercise = Model.ActiveExercise;
}
<div>
    <div>
        <div class="panel panel-default">
            <div class="panel-heading">@exercise.Title</div>
            <div class="panel-body">
                @exercise.Description
            </div>
        </div>


        <div class="solution-form-wrap">

            @{
                var routeValues = new RouteValueDictionary { { "category", Model.NextCategory }, { "exerciseName", Model.NextExercise } };
            }

            @{
                using (Html.BeginForm("PostSolution", "Exercise", FormMethod.Post))
                {
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <input type="hidden" value="@exercise.Category" name="category" />
                        <input type="hidden" value="@exercise.FileName" name="exerciseName" />
                        <textarea class="form-control" rows="5" name="userSolution" id="userSolution" value="@exercise.Code">@exercise.Code</textarea>

                    </div>
                    <div>
                        <button type="submit" onclick="setLastExercise('@Model.ActiveCategory', '@Path.GetFileNameWithoutExtension(Model.ActiveExercise.FileName)')" value="@exercise" class="check-button mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                            CHECK
                        </button>
                        <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" href="/@Model.NextCategory/@Model.NextExercise">NEXT</a>
                    </div>
                }

            }

        </div>
        @{
            if (!string.IsNullOrEmpty(Model.Result))
            {
                <div class="alert alert-info" role="alert">
                    <pre>@Model.Result</pre>
                </div>
            }
        }


        <hr />

        <div class="panel panel-default">
            <label class="collapse panel-heading" for="_1">Hint</label>
            <input id="_1" type="checkbox">
            <div class="panel-body">
                @exercise.Hint
            </div>
        </div>

        <div class="panel panel-default">
            <label class="collapse panel-heading" for="_2">Solution</label>
            <input id="_2" type="checkbox">
            <div class="panel-body">
                @exercise.Solution
            </div>
        </div>

    </div>
</div>

<script>
    function setLastExercise(category, exercise) {
        if ('localStorage' in window && window['localStorage'] !== null) {
            console.log(category);
            localStorage.setItem('category', category);
            localStorage.setItem('exercise', exercise);
        }
    }
</script>

Haskify/Views/Exercise/Index.cshtml
@model Haskify.Models.ExerciseViewModel
<div>
    <h2>HELLO!</h2>

    <p>Want to learn some Haskell?</p>

    <p>Just choose a category from the menu and start hacking! :)</p>
   
    <a id="btnContinue" href="/Math" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">START HACKING</a>
    
</div>


<script>
    $(document).ready(function () {
        getLastExercise();
    });

    function getLastExercise() {
        if (localStorage.length !== 0) {
            var url = "/" + localStorage.getItem("category") + "/" + localStorage.getItem("exercise");
            $("#btnContinue").attr('href', url);
            $("#btnContinue").text("CONTINUE");
        } 
    }
</script>

Haskify/Views/Shared/_Categories.cshtml
@model Haskify.Models.CategoryViewModel

@{
    Layout = null;
}

<div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Exercises</span>
    @foreach (var category in Model.Categories)
            {
        <nav class="mdl-navigation">

            <label class="collapsedMenu mdl-navigation__link @Model.IsCategoryActive(category.CategoryName)" for="@category.CategoryName">@category.CategoryName</label>
            <input id="@category.CategoryName" type="checkbox">
            <ul class="mdl-navigation sub-menu">
                <li>
                    <a class="mdl-navigation__link @Model.IsExerciseActive("Introduction", category.CategoryName)" href="/@category.CategoryName">Introduction</a>
                </li>
                @foreach (var exercise in category.CategoryExercises)
                {
                    <li>
                        <a class="mdl-navigation__link @Model.IsExerciseActive(exercise, category.CategoryName)" href="/@category.CategoryName/@exercise">@exercise</a>
                    </li>
                }
            </ul>
        </nav>
    }

</div>

Haskify/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <!-- Material Design Lite -->
    <script src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
    <!-- Material Design icon font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
    <div class="mdl-layout mdl-js-layout">
        <header class="mdl-layout__header mdl-layout__header--scroll">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <a class="mdl-layout-title" href="/">Haskify</a>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>

            </div>
            <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
                @if (Model.CategoryExercises != null)
            {
                    <a href="/@Model.ActiveCategory" class="mdl-layout__tab">@Model.ActiveCategory</a>
                    foreach (var exercise in Model.CategoryExercises)
                    {
                        <a href="/@Model.ActiveCategory/@exercise" class="mdl-layout__tab @(Model.IsActive(exercise))"> @exercise </a>
                    }
                }
            </div>
        </header>

        @Html.Action("GetCategories", "Exercise")
    </div>

    <div class="container page-content">
        <main class="mdl-layout__content">
            @RenderBody()
        </main>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>